services:
  - type: web
    name: snkrs-backend
    runtime: java
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false